### ISSUE TITLE
QGIS 3.28.5 - Ligne vide dans le journal des messages - colonnes score 

### ISSUE THREAD

**Issue by Julie-Dejante** [CREASIG/QBANO#12]
Bonjour, 
Nous rencontrons un soucis avec l'extension sur le poste d'une collègue (et uniquement sur son poste). 
La couche temporaire est bien créée mais les colonnes "adresse_trouvee" "score" et "type" sont vides (et aucun point n'est créé). 

Quand on regarde dans le journal des messages on voit une ligne vide entre chaque ligne "API" alors que sur mon poste elle n'apparait pas. 

![image](https://user-images.githubusercontent.com/53436697/234781706-be29d8f2-1caa-47fb-935e-4df49b9708d3.png)

Nous avons cherché un peu partout : mise à jour ordinateur, mise à jour windows, mise à jour extension, mise à jour QGIS... Sur les deux postes tout semble pareil mais pourtant nous ne parvenons pas à le faire fonctionner sur un des postes. 
A savoir que sur une version antérieure (on a essayé la 3.4 et la 3.10), l'extension fonctionne correctement.... 

Auriez vous une idée de ce qui peut nous bloquer svp ? 

Merci d'avance

**Comment by CREASIG** [comment]
Bonjour,

Je vous conseille de : 
Fermer QGIS

Renommer les répertoires Qgis en Qgis.old:
C:\Utilisateurs\<identifiant>\AppData\Local\
C:\Utilisateurs\<identifiant>\AppData\Roaming\
Relancer QGIS.

Ça force QGIS à refaire tous les paramètres, mais on perd ceux de l'utilisateur.

Cordialement,

**Comment by Julie-Dejante** [comment]
Bonjour, 

Merci pour votre réponse. 
Nous venons de faire la manipulation mais le problème est toujours là. 
![image](https://user-images.githubusercontent.com/53436697/234793791-de8a44b8-d59b-471b-a29f-9ea2c8a1a02b.png)

Je vous mets les deux captures pour être sûre d'avoir fait ce qu'il fallait, un second répertoire QGIS s'est créé et en effet les paramètres de l'utilisateur ont été réinitialisés. 
![image](https://user-images.githubusercontent.com/53436697/234794100-7f77618c-9b60-4c7a-8069-e9750e2f33bd.png)
 
![image](https://user-images.githubusercontent.com/53436697/234794124-a8846d38-1d35-4ed5-96e5-c71566633705.png)

**Comment by CREASIG** [comment]
Dans le dossier 
C:\Users\<utilisateur>\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QBano

Pouvez-vous remplacer le fichier contenu dans le zip ?

[QBano_dialog.zip](https://github.com/CREASIG/QBANO/files/11342301/QBano_dialog.zip)

**Comment by Julie-Dejante** [comment]
Bonjour, 

Cela a fonctionné. 

Je vous remercie pour votre rapidité et votre efficacité.
